arch: mlp
batch_size: 64
checkpoints_dir: ./checkpoints
code_dim: 512
commit: 0.02
cond_drop_prob: 0.1
cond_mask_prob: 0.0
cuda: True
data_dir: ./dataset/KIT-ML
dataset_name: kit
depth: 3
device: 0
diff_cond_dim: 512
diff_ff_size: 1024
diff_layers: 4
diff_output_dim: 512
diffusion_steps: 50
dilation_growth_rate: 3
down_t: 2
dropout: 0.2
emb_trans_dec: False
eval_every_e: 10
eval_split: test
ext: default
feat_bias: 5
ff_size: 1024
force_mask: False
gamma: 0.1
gumbel_sample: False
input_dim: 512
is_continue: False
is_train: True
kl_name: kl_vae_ver0
latent_dim: 512
layers: 3
log_every: 50
loss_vel: 0.5
lr: 0.0001
lr_anneal_steps: 0
mask_schedule: cosine
max_epoch: 2000
max_motion_length: 196
meta_dir: ./checkpoints/kit/kl_vae_ver0/meta
# No step, setting to max_epoch + 1
milestones: [1500]
milestones_type: batch
mu: 0.99
n_heads: 8
n_layers: 16
name: default_Trans-B_km-sched_EMA_klv0_tnv2
noise_schedule: cosine
output_emb_width: 512
overwrite: False
pad_embedding_type: zero
quantize_dropout_prob: 0.2
recons_loss: l1_smooth
resume_checkpoint: 
save_every_e: 2
save_latest: 500
seed: 10
share_weight: False
sigma_small: True
stride_t: 2
train_platform_type: NoPlatform
unconstrained: False
unit_length: 4
vae_kl_weight: 1e-06
vq_act: relu
vq_norm: None
warm_up_iter: 2000
weight_decay: 0.02
adamw_betas: [0.9, 0.95]
width: 512
window_size: 64